## Take output from a steady state run and generate ICs for alkalinity perturbations

using MAT
using Printf

ss_filename = "/Users/maxrintoul/repos/RADIv2_09_03_2026/logical_investigation/sols_all_20260512_115125.mat";
model_output = matread(ss_filename);

rho_sw_vals = model_output["model_params"]["rho_sw"]
# rho_sw_vals = Float64.(vec(rho_sw_raw))

## Get final model output for each run
fin_sols = model_output["u"][:, :, end, :];
h_sols = reshape(model_output["H"][:, end, :], size(fin_sols)[3], size(fin_sols)[2],1);
fin_sols = cat(fin_sols, h_sols; dims=1); # add final depth profile as last variable in model output for use in perturbation runs

## Variable names for model output (in order)
var_names = ["dO2", "dtCO2", "dtNO3", "dtSO4", "dtPO4", "dtNH4", "dtH2S", "dFeII", "dMnII", 
"dCH4", "dalk", "dalk_alloch", "dalk_aerob", "dalk_anaerob", "dalk_carb", "dCa", "pfoc", 
"psoc", "pFeOH3", "pMnO2", "pcalcite", "paragonite", "pFeS", "pFeS2", "pS0", "pFeOH3_PO4", "H"];


## Create dictionary of final model output for each variable
final_output_dict = Dict(var => fin_sols[i, :, :] for (i, var) in enumerate(var_names));

## Get model inputs for each run

# Input values for steady state run
ss_input_filename = "/Users/maxrintoul/repos/RADIv2_09_03_2026/logical_investigation/input_data_20260512_115125.mat";
steady_state_input = matread(ss_input_filename);

## Define new TA values for perturbations

to_float_vec(x) = x isa Number ? [Float64(x)] : Float64.(vec(x))
base_dalk = Float64(steady_state_input["water_values"]["dalk_w"])
dalk_vals = collect(base_dalk .+ (0.0:0.0001:0.0005))

# dalk_vals = steady_state_input["water_values"]["dalk_w"] .+ (0.0) # :0.0001:0.0005) # example perturbation values for alkalinity in overlying water column (50% decrease, no change, 50% increase)
# dalk_vals = collect(dalk_vals)

## Define perturbation run duration
perturbation_duration = 2.0 # years

## Define function to write new input files for perturbation runs, using steady state output as initial conditions and new TA values for perturbations
function write_perturbation_input_files(steady_state_input::Dict, final_output_dict::Dict, ss_filename::String, ss_input_filename::String, 
    trajectory::Integer, dalk_val::Real, perturbation_duration::Float64)

    dalk_val = Float64(dalk_val)
    perturbation_duration = Float64(perturbation_duration)

    # make filename-safe tag for alkalinity value
    dalk_tag = replace(@sprintf("%.6f", dalk_val), "." => "p", "-" => "m")
    outdir = "/Users/maxrintoul/repos/RADIv2_09_03_2026"
    outpath = joinpath(outdir, "IC_HF2_shallow_fact_perturbation_dalk_" * dalk_tag * ".jl")

    script = """## This file was generated by create_perturbation_inputs.jl from the steady state input file $(ss_input_filename) with final model output from $(ss_filename).
    
    module perturbation_ICs

    export depthSed, dz_top, dz_bot, Nz, tspan, depth, permeability, U, phiInf, phi0, beta, lambda_b, lambda_i,
        T_mean, T_amp, T_period, T_phase, T, S, P, rho_sw, dO2_w, dtCO2_w, dtNO3_w, dtSO4_w, dtNH4_w, dalk_w, 
        dalk_alloch_w, dalk_aerob_w, dalk_anaerob_w, dalk_carb_w, dtPO4_w, dtH2S_w, dCH4_w, dFeII_w, dMnII_w,
        dSi_w, dCa_w, Fpom, Fpom_r, Fpom_s, Fpom_f, FMnO2, FFeOH3, Fcalcite, Faragonite, Fclay, FFeS, FFeS2, FS0, 
        FFeOH3_PO4, rho_p, dO2_i, dtCO2_i, dtNO3_i, dtSO4_i, dtNH4_i, dalk_i, dalk_alloch_i, dalk_aerob_i, 
        dalk_anaerob_i, dalk_carb_i, dtPO4_i, dtH2S_i, dFeII_i, dMnII_i, dCH4_i, dCa_i, dH_i, pfoc_i, psoc_i, proc_i,
        pFeOH3_i, pMnO2_i, pcalcite_i, paragonite_i, pclay_i, pFeS_i, pFeS2_i, pS0_i, pFeOH3_PO4_i,
        calcite_diss_scheme, aragonite_diss_scheme, calcite_precip_scheme, Q10_primary, Q10_secondary, 
        Tref, factorial_T_levels, factorial_Fpom_levels, factorial_U_levels, factorial_P_levels, 
        factorial_calcite_levels, factorial_O_levels, factorial_alk_levels, PERTURBATION_RUN

    PERTURBATION_RUN = true

    const MODULE_DIR = normpath(joinpath(@__DIR__, "modules"))
    include(joinpath(MODULE_DIR, "gsw_rho.jl"))

    # Define model depth steps (all depths in metres)
    depthSed = $(steady_state_input["domain_characteristics"]["depthSed"])  # depth of the sediment
    dz_top = $(steady_state_input["domain_characteristics"]["dz_top"]) # depth resolution at top of sediment
    dz_bot =$(steady_state_input["domain_characteristics"]["dz_bot"])   # depth resolution at bottom of sediment
    Nz = $(steady_state_input["domain_characteristics"]["Nz"])         # number of depth layers

    tspan = (0.0, $(perturbation_duration)) # in years

    # wave
    # wave_height = 1.0 #[m]  # no corresponding value found in read_data_set_max.ipynb
    # wave_period = 6.1 #[s]  # no corresponding value found in read_data_set_max.ipynb
    # wavelength = (9.81*wave_period)/(2*pi) #[m]  # no corresponding value found in read_data_set_max.ipynb

    depth = $(steady_state_input["domain_characteristics"]["depth"]) #[m] average depth of enclosed bay  # no corresponding value found in read_data_set_max.ipynb

    permeability = $(steady_state_input["domain_characteristics"]["permeability"]) # [m^2]  # no corresponding value found in read_data_set_max.ipynb

    # Currents
    U = $(steady_state_input["domain_characteristics"]["U"]) # m/s  # no corresponding value found in read_data_set_max.ipynb

    # Define sediment porosity parameters (weighted fit with phi0 fixed to shallowest)
    phiInf = $(steady_state_input["domain_characteristics"]["phiInf"])
    phi0 = $(steady_state_input["domain_characteristics"]["phi0"])
    beta = $(steady_state_input["domain_characteristics"]["beta"])  # converted from fitted b in cm^-1 to m^-1 

    # Define characteristic depths
    lambda_b = $(steady_state_input["domain_characteristics"]["lambda_b"])  # /m  # no corresponding value found in read_data_set_max.ipynb
    lambda_i = $(steady_state_input["domain_characteristics"]["lambda_i"])  # /m  # no corresponding value found in read_data_set_max.ipynb

    # Define overlying water column properties
    T_mean = $(steady_state_input["domain_characteristics"]["T_mean"]) # °C
    T_amp = $(steady_state_input["domain_characteristics"]["T_amp"]) # °C
    T_period = $(steady_state_input["domain_characteristics"]["T_period"]) # years
    T_phase = $(steady_state_input["domain_characteristics"]["T_phase"]) # years
    T = T_mean # °C, initial temperature for chemistry calculations
    S = $(steady_state_input["domain_characteristics"]["S"])
    P = $(steady_state_input["domain_characteristics"]["P"])  # dbar/depth from CTD bottom-most value
    rho_sw = gsw_rho(S, T, P) # seawater density / kg/m^3

    # Concentrations all in mol/kg
    dO2_w   = $(steady_state_input["factorial_values"]["param_meta_list"][trajectory]["O"])
    dtCO2_w = $(steady_state_input["water_values"]["dtCO2_w"])
    dtNO3_w = $(steady_state_input["water_values"]["dtNO3_w"])
    dtSO4_w = $(steady_state_input["water_values"]["dtSO4_w"])
    dtNH4_w = $(steady_state_input["water_values"]["dtNH4_w"])
    # Define new TA value for perturbation
    dalk_w = $(dalk_val)
    dalk_alloch_w = $(steady_state_input["water_values"]["dalk_alloch_w"])  # Tracer for allochthonous alkalinity input, e.g. from overlying water column. Assume all initial alk is allochthonous for simplicity.
    dalk_aerob_w = $(steady_state_input["water_values"]["dalk_aerob_w"])            # Tracer for alkalinity produced from aerobic respiration
    dalk_anaerob_w = $(steady_state_input["water_values"]["dalk_anaerob_w"])          # Tracer for alkalinity produced from anaerobic respiration
    dalk_carb_w = $(steady_state_input["water_values"]["dalk_carb_w"])             # Tracer for alkalinity produced from carbonate dissolution
    
    dtPO4_w = $(steady_state_input["water_values"]["dtPO4_w"]) 
    dtH2S_w = $(steady_state_input["water_values"]["dtH2S_w"])         
    dCH4_w  = $(steady_state_input["water_values"]["dCH4_w"])     
    dFeII_w = $(steady_state_input["water_values"]["dFeII_w"]) 
    dMnII_w = $(steady_state_input["water_values"]["dMnII_w"])
    dSi_w   = $(steady_state_input["water_values"]["dSi_w"])  
    dCa_w   = 0.02128 / 40.087 * S / 1.80655 #mol/kg, calculated from salinity using Ca:salinity ratio in seawater (Millero, 2013)  

    # Define organic matter flux to the surface sediment    
    Fpom = $(steady_state_input["factorial_values"]["param_meta_list"][trajectory]["Fpom"])
    Fpom_r = $(steady_state_input["solid_fluxes"]["Fpom_r"])
    Fpom_s = $(steady_state_input["solid_fluxes"]["Fpom_s"])
    Fpom_f = $(steady_state_input["solid_fluxes"]["Fpom_f"])
    FMnO2 = $(steady_state_input["solid_fluxes"]["FMnO2"])
    FFeOH3 = $(steady_state_input["solid_fluxes"]["FFeOH3"])
    Fcalcite = $(steady_state_input["factorial_values"]["param_meta_list"][trajectory]["Fcalcite"])
    Faragonite = $(steady_state_input["solid_fluxes"]["Faragonite"])
    Fclay = $(steady_state_input["solid_fluxes"]["Fclay"])
    FFeS = $(steady_state_input["solid_fluxes"]["FFeS"])
    FFeS2 = $(steady_state_input["solid_fluxes"]["FFeS2"])
    FS0 = $(steady_state_input["solid_fluxes"]["FS0"])
    FFeOH3_PO4 = $(steady_state_input["solid_fluxes"]["FFeOH3_PO4"])
    rho_p = $(steady_state_input["solid_fluxes"]["rho_p"])

    # Define initial conditions within the sediment (scalars or arrays)
    dO2_i   = $(final_output_dict["dO2"][:, trajectory] ./ rho_sw_vals) # convert from mol/m^3 to mol/kg using depth-dependent seawater density values from model output
    dtCO2_i = $(final_output_dict["dtCO2"][:, trajectory] ./ rho_sw_vals)
    dtNO3_i = $(final_output_dict["dtNO3"][:, trajectory] ./ rho_sw_vals)
    dtSO4_i = $(final_output_dict["dtSO4"][:, trajectory] ./ rho_sw_vals)
    dtNH4_i = $(final_output_dict["dtNH4"][:, trajectory] ./ rho_sw_vals)
    dalk_i  = $(final_output_dict["dalk"][:, trajectory] ./ rho_sw_vals)

    dalk_alloch_i  = $(final_output_dict["dalk_alloch"][:, trajectory] ./ rho_sw_vals)             # Tracer for allochthonous alkalinity input, e.g. from overlying water column. Assume all initial alk is allochthonous for simplicity.
    dalk_aerob_i   = $(final_output_dict["dalk_aerob"][:, trajectory] ./ rho_sw_vals)              # Tracer for alkalinity produced from aerobic respiration
    dalk_anaerob_i = $(final_output_dict["dalk_anaerob"][:, trajectory] ./ rho_sw_vals)            # Tracer for alkalinity produced from anaerobic respiration
    dalk_carb_i    = $(final_output_dict["dalk_carb"][:, trajectory] ./ rho_sw_vals)               # Tracer for alkalinity produced from carbonate dissolution

    dtPO4_i = $(final_output_dict["dtPO4"][:, trajectory] ./ rho_sw_vals)  # no corresponding value found in read_data_set_max.ipynb
    dtH2S_i = $(final_output_dict["dtH2S"][:, trajectory] ./ rho_sw_vals)  # no corresponding value found in read_data_set_max.ipynb
    dFeII_i = $(final_output_dict["dFeII"][:, trajectory] ./ rho_sw_vals)  # no corresponding value found in read_data_set_max.ipynb
    dMnII_i = $(final_output_dict["dMnII"][:, trajectory] ./ rho_sw_vals)  # no corresponding value found in read_data_set_max.ipynb
    dCH4_i  = $(final_output_dict["dCH4"][:, trajectory] ./ rho_sw_vals)   # no corresponding value found in read_data_set_max.ipynb
    dCa_i   = $(final_output_dict["dCa"][:, trajectory] ./ rho_sw_vals)    # no corresponding value found in read_data_set_max.ipynb
    dH_i    = $(final_output_dict["H"][:, trajectory] ./ rho_sw_vals)      # depth profile from final model output, to be used in perturbation runs

    pfoc_i       = $(final_output_dict["pfoc"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    psoc_i       = $(final_output_dict["psoc"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    proc_i       = 6.0e2 # Not used in model beside initial conditions, so set to arbitrary value for now.  # no corresponding value found in read_data_set_max.ipynb
    pFeOH3_i     = $(final_output_dict["pFeOH3"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    pMnO2_i      = $(final_output_dict["pMnO2"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    pcalcite_i   = $(final_output_dict["pcalcite"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    paragonite_i = $(final_output_dict["paragonite"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    pclay_i      = 1.0e3 # Not used in model beside initial conditions, so set to arbitrary value for now.  # no corresponding value found in read_data_set_max.ipynb
    pFeS_i       = $(final_output_dict["pFeS"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    pFeS2_i      = $(final_output_dict["pFeS2"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    pS0_i        = $(final_output_dict["pS0"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb
    pFeOH3_PO4_i = $(final_output_dict["pFeOH3_PO4"][:, trajectory])  # no corresponding value found in read_data_set_max.ipynb

    # Define dissolution scheme for CaCO3 (1 = base RADI, 2 = temp dependent dissolution)
    calcite_diss_scheme = $(steady_state_input["carb_schemes"]["calcite_diss_scheme"])
    aragonite_diss_scheme = $(steady_state_input["carb_schemes"]["aragonite_diss_scheme"])

    # Define precipitation scheme for calcite (1 = base RADI, 2 = temp dependent precipitation)
    calcite_precip_scheme = $(steady_state_input["carb_schemes"]["calcite_precip_scheme"])

    # Define Q10 for secondary reactions
    Q10_primary = $(steady_state_input["Q10_setup"]["Q10_primary"])
    Q10_secondary = $(steady_state_input["Q10_setup"]["Q10_secondary"])
    Tref = $(steady_state_input["Q10_setup"]["Tref"])

    # Factoriral alk levels for perturbation runs
    factorial_alk_levels      = $(dalk_vals)

    end

    """

    open(outpath,"w") do io
        write(io, script);
    end

    return outpath
end

write_perturbation_input_files(steady_state_input, final_output_dict, ss_filename, ss_input_filename, 1, dalk_vals, perturbation_duration);



# written_files = String[]
# for dv in dalk_vals
#     fp = write_perturbation_input_files(
#         steady_state_input,
#         final_output_dict,
#         ss_filename,
#         ss_input_filename,
#         1,                    # trajectory
#         dv,
#         perturbation_duration
#     )
#     push!(written_files, fp)
# end

# println("Wrote ", length(written_files), " files")
# foreach(println, written_files)